volumes:
  mysql-data:
  npm_data:

networks:
  default:
    driver: bridge

services:
  app:
    build:
      dockerfile: ./.dev/Dockerfile
    container_name: app
    volumes:
      - .:/app
      - ./.dev/nginx.conf:/opt/docker/etc/nginx/vhost.conf

    working_dir: /app
    depends_on:
      - mysql
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - default

  mysql:
    image: mysql:5.7.44
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
    restart: unless-stopped

