services:
  app:
    image: webdevops/php-nginx-dev:8.3-alpine
    container_name: app
    volumes:
      - ./app:/app
#      - ./.dev/nginx.conf:/etc/nginx/nginx.conf
      - ./.dev/nginx.conf:/opt/docker/etc/nginx/vhost.conf
    working_dir: /app
    networks:
      - default
    depends_on:
      - mysql
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - "80:80"

  mysql:
    image: mysql:5.7.44
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

volumes:
  mysql-data:

networks:
  default: